---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/4865/workspace/MavenAnsible-CICD/target/MavenAnsibleWebapp.war"
        dest: "/opt/tomcat/webapps/MavenAnsibleWebapp.war"
        remote_src: no
    - name: Restart Tomcat (manual installation)
      become: yes
      ansible.builtin.shell: "/opt/tomcat/bin/shutdown.sh && /opt/tomcat/bin/startup.sh"
